# Etapa de desarrollo
FROM node:23.0.0-alpine3.20 as builder

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copia el resto del código de la aplicación
COPY . .

RUN npm run build

FROM node:23.0.0-alpine3.20

WORKDIR /app

COPY --from=builder /app .

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 8080

# Define el comando para ejecutar la aplicación
CMD ["node", "dist/index.js"]