export const envSchema = {
  type: 'object',
  required: [
    'PORT',
    'DB_PORT',
    'DB_HOST',
    'DB_USER',
    'DB_NAME',
    'DB_PASSWORD',
    'JWT_SECRET',
    'CLOUDINARY_CLOUD_NAME',
    'CLOUDINARY_API_KEY',
    'CLOUDINARY_API_SECRET',
    'RESEND_API_KEY',
    'FRONTEND_URL',
    'FRONTEND_URL_PROD',
    'NODE_ENV',
    'LOG_LEVEL',
    'N8N_CHAT_PROD_URL',
    'N8N_CHAT_TEST_URL',
    'N8N_RAG_PROD_URL',
    'N8N_RAG_TEST_URL',
    'IDRIVE_ENDPOINT',
    'IDRIVE_PUBLIC_URL',
    'IDRIVE_ACCESS_KEY',
    'IDRIVE_SECRET_KEY',
    'IDRIVE_BUCKET',
    'KEY_FILE_PATH_GD',
    'SCOPES_GD',
    'GOOGLE_DRIVE_TASKS_FOLDER_ID',
    'STORJ_ENDPOINT',
    'STORJ_ACCESS_KEY',
    'STORJ_SECRET_KEY',
    'STORJ_BUCKET',
    'STORJ_PUBLIC_ID',
  ],
  properties: {
    PORT: { type: 'number', default: 3000 },
    DB_PORT: { type: 'number' },
    DB_HOST: { type: 'string' },
    DB_USER: { type: 'string' },
    DB_NAME: { type: 'string' },
    DB_PASSWORD: { type: 'string' },
    JWT_SECRET: { type: 'string' },
    CLOUDINARY_CLOUD_NAME: { type: 'string' },
    CLOUDINARY_API_KEY: { type: 'string' },
    CLOUDINARY_API_SECRET: { type: 'string' },
    RESEND_API_KEY: { type: 'string' },
    FRONTEND_URL: { type: 'string' },
    FRONTEND_URL_PROD: { type: 'string' },
    NODE_ENV: { type: 'string' },
    LOG_LEVEL: { type: 'string' },
    N8N_CHAT_PROD_URL: { type: 'string' },
    N8N_CHAT_TEST_URL: { type: 'string' },
    N8N_RAG_PROD_URL: { type: 'string' },
    N8N_RAG_TEST_URL: { type: 'string' },
    IDRIVE_ENDPOINT: { type: 'string' },
    IDRIVE_PUBLIC_URL: { type: 'string' },
    IDRIVE_ACCESS_KEY: { type: 'string' },
    IDRIVE_SECRET_KEY: { type: 'string' },
    IDRIVE_BUCKET: { type: 'string' },
    KEY_FILE_PATH_GD: { type: 'string' },
    SCOPES_GD: { type: 'string' },
    GOOGLE_DRIVE_TASKS_FOLDER_ID: { type: 'string' },
    STORJ_ENDPOINT: { type: 'string' },
    STORJ_ACCESS_KEY: { type: 'string' },
    STORJ_SECRET_KEY: { type: 'string' },
    STORJ_BUCKET: { type: 'string' },
    STORJ_PUBLIC_ID: { type: 'string' },
  },
};
