export const envSchema = {
  type: 'object',
  required: [
    'PORT',
    'DB_PORT',
    'DB_HOST',
    'DB_USER',
    'DB_NAME',
    'DB_PASSWORD',
    'JWT_SECRET_KEY',
    'CLOUDINARY_CLOUD_NAME',
    'CLOUDINARY_API_KEY',
    'CLOUDINARY_API_SECRET',
    'RESEND_API_KEY',
    'FRONTEND_URL',
    'FRONTEND_URL_PROD',
    'NODE_ENV',
    'LOG_LEVEL',
    'N8N_CHAT_PROD_URL',
    'N8N_CHAT_TEST_URL',
    'N8N_RAG_PROD_URL',
    'N8N_RAG_TEST_URL',
  ],
  properties: {
    PORT: { type: 'number', default: 3000 },
    DB_PORT: { type: 'number' },
    DB_HOST: { type: 'string' },
    DB_USER: { type: 'string' },
    DB_NAME: { type: 'string' },
    DB_PASSWORD: { type: 'string' },
    JWT_SECRET_KEY: { type: 'string' },
    CLOUDINARY_CLOUD_NAME: { type: 'string' },
    CLOUDINARY_API_KEY: { type: 'string' },
    CLOUDINARY_API_SECRET: { type: 'string' },
    RESEND_API_KEY: { type: 'string' },
    FRONTEND_URL: { type: 'string' },
    FRONTEND_URL_PROD: { type: 'string' },
    NODE_ENV: { type: 'string' },
    LOG_LEVEL: { type: 'string' },
    N8N_CHAT_PROD_URL: { type: 'string' },
    N8N_CHAT_TEST_URL: { type: 'string' },
    N8N_RAG_PROD_URL: { type: 'string' },
    N8N_RAG_TEST_URL: { type: 'string' },
  },
};
