export const envSchema = {
  type: 'object',
  required: [
    'PORT',
    'HOST',
    'DB_PORT',
    'DB_HOST',
    'DB_USER',
    'DB_NAME',
    'DB_PASSWORD',
    'JWT_SECRET_KEY',
    'CLOUDINARY_CLOUD_NAME',
    'CLOUDINARY_API_KEY',
    'CLOUDINARY_API_SECRET',
    'RESEND_API_KEY',
    'FRONTEND_URL',
    'FRONTEND_URL_PROD',
    'NODE_ENV',
    'LOG_LEVEL',
    'N8N_CHAT_PROD_URL',
    'N8N_CHAT_TEST_URL',
    'N8N_RAG_PROD_URL',
    'N8N_RAG_TEST_URL',
    'GOOGLE_PALM_HOST',
    'GOOGLE_GEMINI_API_KEY',
    'SUPABASE_HOST',
    'SERVICE_ROLE_SECRET',
    'POSTGRES_DB_HOST',
    'POSTGRES_DB_PORT',
    'POSTGRES_DB_NAME',
    'POSTGRES_DB_USER',
    'POSTGRES_DB_PASSWORD',
    'POSTGRES_DB_SSL',
  ],
  properties: {
    PORT: { type: 'number', default: 3000 },
    HOST: { type: 'string', default: 'localhost' },
    DB_PORT: { type: 'number' },
    DB_HOST: { type: 'string' },
    DB_USER: { type: 'string' },
    DB_NAME: { type: 'string' },
    DB_PASSWORD: { type: 'string' },
    JWT_SECRET_KEY: { type: 'string' },
    CLOUDINARY_CLOUD_NAME: { type: 'string' },
    CLOUDINARY_API_KEY: { type: 'string' },
    CLOUDINARY_API_SECRET: { type: 'string' },
    RESEND_API_KEY: { type: 'string' },
    FRONTEND_URL: { type: 'string' },
    FRONTEND_URL_PROD: { type: 'string' },
    NODE_ENV: { type: 'string' },
    LOG_LEVEL: { type: 'string' },
    N8N_CHAT_PROD_URL: { type: 'string' },
    N8N_CHAT_TEST_URL: { type: 'string' },
    N8N_RAG_PROD_URL: { type: 'string' },
    N8N_RAG_TEST_URL: { type: 'string' },
    GOOGLE_PALM_HOST: { type: 'string' },
    GOOGLE_GEMINI_API_KEY: { type: 'string' },
    SUPABASE_HOST: { type: 'string' },
    SERVICE_ROLE_SECRET: { type: 'string' },
    POSTGRES_DB_HOST: { type: 'string' },
    POSTGRES_DB_PORT: { type: 'number' },
    POSTGRES_DB_NAME: { type: 'string' },
    POSTGRES_DB_USER: { type: 'string' },
    POSTGRES_DB_PASSWORD: { type: 'string' },
    POSTGRES_DB_SSL: { type: 'boolean' },
  },
} as const;
